# Generated by Django 4.1.1 on 2022-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_items', models.CharField(max_length=200)),
                ('in_and_out', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('fifo', models.CharField(max_length=200)),
            ],
        ),
    ]
